### ISSUE TITLE
ITV Downloads failing after update to 1.24.0

### ISSUE THREAD

**Issue by pebceb** [Ascoware/get-iplayer-automator#410]
Good morning and thanks again for all you do Scott.

I updated to 1.24.0 and on my M1 Mac all all ITV and BBC shows are downloading fine.

On my MacBook Pro (not M1) after the update the ITV shows are failing and the BBC shows are fine. It says "Problem Unknown.  Please submit a bug from the application menu."  I cannot see where to submit a bug in any of the menus?

Any idea what might be causing this?

Thanks.

Peter

**Comment by SOLOSAIR** [comment]
Just as a side note to this, itv progs now either don't make it to the tv app or don't appear in it as telly but 'home movie' necessitating a manual change for it to be listed with the other telly programmes imported.  Anyone else seeing this?

**Comment by pebceb** [comment]
Yes I noticed the same thing for the ones that did work on my M1 Mac.  Still cannot get it to work on my Intel Macbook.  Even got the previous version from Time Machine and still not working.

**Comment by skovatch** [comment]
Oh no! You're right! I had that working for a while but now it isn't. Sorry about that. I'll try to get a fix out soon.

**Comment by skovatch** [comment]
fixed in 1.24.1

**Comment by pebceb** [comment]
Good morning Scott.

I just did the update on my MacBook Pro (Intel) and the ITV shows are still failing to download.  Still getting unknown error.

Any suggestions?

Peter

**Comment by ian02054** [comment]
Yes, I saw my itv going to "home videos" last night
